spring:
  profiles:
    active:
    - dev
    - test

---
spring:
  application:
    name: springcloud-demo-config-dev
  profiles: dev

---
spring:
  application:
    name: springcloud-demo-config-test
  profiles: test
